<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cadastrar Informações de Contato</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <form action="" method="">
          UF:<select name="uf" id="uf"></select>
          CIDADE:<select name="cidade" id="cidade"></select>
          <br>
          BAIRRO: <input type="text" name="bairro">
          <br>
          TELEFONE: <input type="text" name="telefone">
          <button type="button" class="btn btn-primary">
            Salvar
          </button>
         </form>
      </div>     
    </div>
  </div>
</div>